apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: fs4.rtvslo.si
    path: "/Kubernetes"

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv-1
# spec:
#   capacity:
#     storage: 50Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   local:
#     path: ccc
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - microkube1
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv-2
# spec:
#   capacity:
#     storage: 20Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete

#   local:
#     path: /var/snap/microk8s/ccc/pv-2
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - microkube1