# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nfs
# spec:
#   capacity:
#     storage: 40Gi
#   accessModes:
#     - ReadWriteOnce
#   nfs:
#     server: fs4.rtvslo.si
#     path: "/Kubernetes"

# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /local_volume/v1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - microkube1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-2
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /local_volume/v2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - microkube1