apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
<<<<<<< HEAD
  name: node-ingress
=======
  name: nginx-ingress
>>>>>>> e429864e921e76c8973c4a491eba5ce9605ec5c7
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: public
  rules:
<<<<<<< HEAD
    - host: wp.micro.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
    - host: echo.micro.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-service
                port:
                  number: 8000
=======
  - host: wp.micro.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
  - host: echo.micro.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-service
            port:
              number: 8000
>>>>>>> e429864e921e76c8973c4a491eba5ce9605ec5c7
