apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress2
  template:
    metadata:
      labels:
        app: wordpress2
    spec:
      containers:
        - name: wordpress2
          image: wordpress:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress2
spec:
  selector:
    app: wordpress2
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress2
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: wp.micro.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress2
                port:
                  number: 80
  tls:
    - hosts:
      - wp.micro.com